In [9]:
import numpy as np
import scipy as sp

In [34]:
%precision 3　

'%.3f'

In [35]:
human_data = np.array([170, 171, 173, 173, 175, 175, 176, 177, 180, 180])
human_data

array([170, 171, 173, 173, 175, 175, 176, 177, 180, 180])

In [36]:
sp.sum(human_data)#sum the human_data

1750

In [37]:
len(human_data)#count the human_data

10

In [38]:
N = len(human_data)
sum_value = sp.sum(human_data)
me = sum_value / N
me #find the average

175.0

In [39]:
sp.mean(human_data)# find the average of human_data

175.0

In [40]:
human_data - me #subtracted average from human_data

array([-5., -4., -2., -2.,  0.,  0.,  1.,  2.,  5.,  5.])

In [41]:
(human_data - me) ** 2 #subtracted average from human_data, squarted.

array([25., 16.,  4.,  4.,  0.,  0.,  1.,  4., 25., 25.])

In [42]:
sp.sum((human_data - me) ** 2) 

104.0

In [43]:
sp.var(human_data, ddof = 0) #find the sample variance.

10.4

In [44]:
sp.var(human_data, ddof = 1) #find the unbias variance.

11.555555555555555

In [45]:
sigma = sp.sum((human_data -me) ** 2) / (N - 1)
sigma #find the standard deviation

11.555555555555555

In [46]:
sigma = sp.sqrt(sigma)
sigma

3.39934634239519

In [47]:
sp.std(human_data, ddof = 1)

3.39934634239519

**標準化**

データの平均を０に，標準偏差を１に変換すること

In [48]:
print(human_data - me)
print(sp.mean(human_data - me))
print(human_data / sigma)
print(sp.std(human_data / sigma, ddof = 1))
standard = (human_data - me) / sigma
print(standard)
print(sp.mean(standard))
print(sp.std(standard, ddof = 1))
# standardize


[-5. -4. -2. -2.  0.  0.  1.  2.  5.  5.]
0.0
[50.01  50.304 50.892 50.892 51.48  51.48  51.775 52.069 52.951 52.951]
1.0000000000000004
[-1.471 -1.177 -0.588 -0.588  0.     0.     0.294  0.588  1.471  1.471]
0.0
1.0


In [49]:
sp.amax(human_data) #find the max of human_data

180

In [50]:
sp.amin(human_data) #find the min of human_data

170

In [51]:
sp.median(human_data) #find the median of human_data

175.0

In [52]:
human_data2 = np.array([170, 171, 173, 173, 175, 175, 176, 177, 180, 180, 2000])
sp.mean(human_data2)

340.90909090909093

In [53]:
sp.median(human_data2)

175.0

In [54]:
from scipy import stats

In [55]:
stats.scoreatpercentile(human_data, 25)

173.0

In [56]:
stats.scoreatpercentile(human_data, 75)

176.75

In [57]:
stats.scoreatpercentile(human_data, 100)

180.0