## 重回帰分析とは

* そもそも回帰分析とは何か
→　関数をデータに当てはめることにより、ある変数yの変動を別の変数xの変動により説明・予測・影響関係を検討するための手法。

説明したい（予測したい）をy（目的変数）として、そのyを説明するための変数を説明変数と呼ぶ。

説明変数（x）が一つのモデルのことを単回帰分析と呼ぶ→　　$$y=a_{0}+a_{1}x_{1}$$

$$y=a_{0}+a_{1}x_{1}+a_{2}x_{2}+a_{3}x_{3}+ ・・・ + a_{n}x_{n}$$

In [54]:
import numpy as np
import pandas as pd
import scipy as sp
import matplotlib.pyplot as plt
%matplotlib inline
from sklearn.linear_model import LinearRegression

In [10]:
from sklearn.datasets import load_boston
boston = load_boston()
print(boston.DESCR)

.. _boston_dataset:

Boston house prices dataset
---------------------------

**Data Set Characteristics:**  

    :Number of Instances: 506 

    :Number of Attributes: 13 numeric/categorical predictive. Median Value (attribute 14) is usually the target.

    :Attribute Information (in order):
        - CRIM     per capita crime rate by town
        - ZN       proportion of residential land zoned for lots over 25,000 sq.ft.
        - INDUS    proportion of non-retail business acres per town
        - CHAS     Charles River dummy variable (= 1 if tract bounds river; 0 otherwise)
        - NOX      nitric oxides concentration (parts per 10 million)
        - RM       average number of rooms per dwelling
        - AGE      proportion of owner-occupied units built prior to 1940
        - DIS      weighted distances to five Boston employment centres
        - RAD      index of accessibility to radial highways
        - TAX      full-value property-tax rate per $10,000
        - PTRATIO  pu

In [93]:
print("Boston feature names :\n{}".format(boston.feature_names))

Boston feature names :
['CRIM' 'ZN' 'INDUS' 'CHAS' 'NOX' 'RM' 'AGE' 'DIS' 'RAD' 'TAX' 'PTRATIO'
 'B' 'LSTAT']


In [49]:
df = pd.DataFrame(data=boston["data"], columns=boston["feature_names"])
df["price"] = pd.DataFrame(boston.target)
df.head()

CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD    TAX  \
0  0.00632  18.0   2.31   0.0  0.538  6.575  65.2  4.0900  1.0  296.0   
1  0.02731   0.0   7.07   0.0  0.469  6.421  78.9  4.9671  2.0  242.0   
2  0.02729   0.0   7.07   0.0  0.469  7.185  61.1  4.9671  2.0  242.0   
3  0.03237   0.0   2.18   0.0  0.458  6.998  45.8  6.0622  3.0  222.0   
4  0.06905   0.0   2.18   0.0  0.458  7.147  54.2  6.0622  3.0  222.0   

   PTRATIO       B  LSTAT  price  
0     15.3  396.90   4.98   24.0  
1     17.8  396.90   9.14   21.6  
2     17.8  392.83   4.03   34.7  
3     18.7  394.63   2.94   33.4  
4     18.7  396.90   5.33   36.2

In [12]:
Y = df['price']
X = df.drop("price", axis=1)

In [14]:
model = LinearRegression()

In [25]:
model.fit(X,Y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [38]:
coefficient = model.coef_
df_coeff = pd.DataFrame(index=X.columns, data = coefficient, columns=["coefficient"])

In [46]:
print("Intercept of boston model:{}".format(model.intercept_))
df_coeff

Intercept of boston model:36.45948838509015


coefficient
CRIM       -0.108011
ZN          0.046420
INDUS       0.020559
CHAS        2.686734
NOX       -17.766611
RM          3.809865
AGE         0.000692
DIS        -1.475567
RAD         0.306049
TAX        -0.012335
PTRATIO    -0.952747
B           0.009312
LSTAT      -0.524758

In [48]:
model.score(X,Y)

0.7406426641094095

In [79]:
from sklearn.datasets import load_boston
boston = load_boston()

In [80]:
df_ob = pd.DataFrame(boston.target, columns=["Price"])

In [81]:
df_ex = pd.DataFrame(boston.data, columns=boston.feature_names)

In [82]:
df = pd.concat([df_ob, df_ex], axis=1)

In [83]:
df

Price     CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD  \
0     24.0  0.00632  18.0   2.31   0.0  0.538  6.575  65.2  4.0900  1.0   
1     21.6  0.02731   0.0   7.07   0.0  0.469  6.421  78.9  4.9671  2.0   
2     34.7  0.02729   0.0   7.07   0.0  0.469  7.185  61.1  4.9671  2.0   
3     33.4  0.03237   0.0   2.18   0.0  0.458  6.998  45.8  6.0622  3.0   
4     36.2  0.06905   0.0   2.18   0.0  0.458  7.147  54.2  6.0622  3.0   
..     ...      ...   ...    ...   ...    ...    ...   ...     ...  ...   
501   22.4  0.06263   0.0  11.93   0.0  0.573  6.593  69.1  2.4786  1.0   
502   20.6  0.04527   0.0  11.93   0.0  0.573  6.120  76.7  2.2875  1.0   
503   23.9  0.06076   0.0  11.93   0.0  0.573  6.976  91.0  2.1675  1.0   
504   22.0  0.10959   0.0  11.93   0.0  0.573  6.794  89.3  2.3889  1.0   
505   11.9  0.04741   0.0  11.93   0.0  0.573  6.030  80.8  2.5050  1.0   

       TAX  PTRATIO       B  LSTAT  
0    296.0     15.3  396.90   4.98  
1    242.0     17.8  396.90   9.14  
2    242.0     17.8  392.83   4.03  
3    222.0     18.7  394.63   2.94  
4    222.0     18.7  396.90   5.33  
..     ...      ...     ...    ...  
501  273.0     21.0  391.99   9.67  
502  273.0     21.0  396.90   9.08  
503  273.0     21.0  396.90   5.64  
504  273.0     21.0  393.45   6.48  
505  273.0     21.0  396.90   7.88  

[506 rows x 14 columns]

In [84]:
df_array = np.array(df)
print(df_array)

[[2.4000e+01 6.3200e-03 1.8000e+01 ... 1.5300e+01 3.9690e+02 4.9800e+00]
 [2.1600e+01 2.7310e-02 0.0000e+00 ... 1.7800e+01 3.9690e+02 9.1400e+00]
 [3.4700e+01 2.7290e-02 0.0000e+00 ... 1.7800e+01 3.9283e+02 4.0300e+00]
 ...
 [2.3900e+01 6.0760e-02 0.0000e+00 ... 2.1000e+01 3.9690e+02 5.6400e+00]
 [2.2000e+01 1.0959e-01 0.0000e+00 ... 2.1000e+01 3.9345e+02 6.4800e+00]
 [1.1900e+01 4.7410e-02 0.0000e+00 ... 2.1000e+01 3.9690e+02 7.8800e+00]]


In [87]:
cov = np.cov(df_array, rowvar=0, bias=0)
cov

array([[ 8.45867236e+01, -3.07185080e+01,  7.73151755e+01,
        -3.05208228e+01,  4.09409463e-01, -4.55412432e-01,
         4.49344588e+00, -9.75890166e+01,  4.84022864e+00,
        -3.05612280e+01, -7.26255716e+02, -1.01106571e+01,
         2.79989834e+02, -4.84475383e+01],
       [-3.07185080e+01,  7.39865782e+01, -4.02159560e+01,
         2.39923388e+01, -1.22108643e-01,  4.19593894e-01,
        -1.32503785e+00,  8.54053223e+01, -6.87672154e+00,
         4.68477610e+01,  8.44821538e+02,  5.39933079e+00,
        -3.02381816e+02,  2.79861679e+01],
       [ 7.73151755e+01, -4.02159560e+01,  5.43936814e+02,
        -8.54126481e+01, -2.52925293e-01, -1.39614820e+00,
         5.11251341e+00, -3.73901548e+02,  3.26293041e+01,
        -6.33486949e+01, -1.23645374e+03, -1.97765707e+01,
         3.73721402e+02, -6.87830369e+01],
       [-3.05208228e+01,  2.39923388e+01, -8.54126481e+01,
         4.70644425e+01,  1.09668806e-01,  6.07073693e-01,
        -1.88795657e+00,  1.24513903e+02, -1.

In [89]:
covA = cov[1:, 1:]
covB = cov[1:, 0]
covB = covB.reshape(13,1)

covA_inv = np.linalg.inv(covA)

coef = np.dot(covA_inv, covB)
print(coef)

[[-1.08011358e-01]
 [ 4.64204584e-02]
 [ 2.05586264e-02]
 [ 2.68673382e+00]
 [-1.77666112e+01]
 [ 3.80986521e+00]
 [ 6.92224640e-04]
 [-1.47556685e+00]
 [ 3.06049479e-01]
 [-1.23345939e-02]
 [-9.52747232e-01]
 [ 9.31168327e-03]
 [-5.24758378e-01]]


In [92]:
df_coeff = pd.DataFrame(index=X.columns, data = coef, columns=["coefficient"])
df_coeff

coefficient
CRIM       -0.108011
ZN          0.046420
INDUS       0.020559
CHAS        2.686734
NOX       -17.766611
RM          3.809865
AGE         0.000692
DIS        -1.475567
RAD         0.306049
TAX        -0.012335
PTRATIO    -0.952747
B           0.009312
LSTAT      -0.524758